### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by jrson83** [amiryousefi/laravel-permission#2]
Hey, I really like the Plugin and would like to use it, but I'm having some problems with installation.
For installation I made all the following steps, but when I navigate to my assigned route with role admin, I get redirected to my 404 page.

I installed via composer and run `php artisan migrate`. Then I created a Seeder:

```
<?php

use Illuminate\Database\Seeder;
use Amir\Permission\Models\Role;

class RolesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       	        Role::firstOrCreate(['name' => 'admin']);
		Role::firstOrCreate(['name' => 'moderator']);
		Role::firstOrCreate(['name' => 'jakob']);
		Role::firstOrCreate(['name' => 'user']);
    }
}
```
Then I run `artisan db:seed --class=RolesTableSeeder`.

Then I copied over your `src/Middleware/AuthRoles.php` to `App\Http\Middleware\AuthRoles.php`.
In `App\ḨTTP\Kernel.php` I registered the Middleware:
```
protected $routeMiddleware = [
        ...
        'auth.role' => \App\Http\Middleware\AuthRoles::class,
        ...
    ];
```
After I setup my routes `routes\web.php`:
```
Route::group([
    'middleware' => 'auth.role',
    'prefix' => 'test',
    'role' => 'admin',
],function (){
    Route::get('/test', 'MyTest@index');
});
```
And run `php artisan permissions:generate`.
Then I set my user profile table role_id in phpmyadmin to 1 (admin).

EDIT: After i registered the provider in `config\app.php`
```
'providers' => [
    ....
    Amir\Permission\LaravelPermissionServiceProvider::class,
    ....
],
```

All roles are in the db table, all permissions are in the db table and there is also the permission_role inserted in the database. Now when I goto my route /test I get redireted to 404 Page.
Can you help me?

**Comment by amiryousefi** [comment]
The 404 error is not one of this package's errors.
Are you sure you are checking the write URL?
According to the documentation, you may need to go to the BASE_URL/test/test Because you added a prefix to your group.
https://laravel.com/docs/7.x/routing#route-group-prefixes
On the other hand, you don't need to copy the middleware to your application or register it. The package handles this itself. You didn't need to add the service provider either.
Of course, you can extend all packages class in your source code, which is a cleaner way to customize it.
Let me know if you need any further help.

**Comment by jrson83** [comment]
I didn't know what the prefix was about. I just removed the `'prefix' =>` in my route and now it's working fine. Thank you very much for this awesome plugin!

One more question. Is it possible to make a page to `users` (so everyone) accessible and check in blade if a user is an admin? I need to make a page accessible for everyone, but the admin should see a link which normal users don't see.

**Comment by amiryousefi** [comment]
To make part of the blade file available only  to a role, you can check for the user's role in your blade: 
`auth()->user()->role_id`.

Your blade file will look like this:
```
@if(auth()->user()->role_id == 1)
   // some part of blade
@endif
```
Also, you can use `HasRoles` trait in your user model.
```PHP
// dont't forget to add HasRoles trait...
use Amir\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    ...
```
So you can get the role in your blade like this
```PHP
@if(auth()->user()->role()->name == 'admin')
    // some part of blade
@endif
```
