### ISSUE TITLE
Assign more then 1 role to a route

### ISSUE THREAD

**Issue by jrson83** [amiryousefi/laravel-permission#3]
How can I assign more then one role to a route? I tried this, but its not working:
```
Route::group([
    'middleware' => 'auth.role',
    'role' => ['moderator', 'admin'],
]
```

**Comment by amiryousefi** [comment]
This isn't available right now. But you can add this via a seeder or by adding the roles id to the permissions id.

Of course, I will add this feature soon.

**Comment by jrson83** [comment]
OK Thanks for the Info.
